spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root

    url: jdbc:mysql://47.96.89.99:3306/dcxevaluation?serverTimezone=Hongkong&allowMultiQueries=true #阿里服务器 3426
    password: ytaotao

    #url: jdbc:mysql://125.220.157.101:3306/dcxevaluation?serverTimezone=Hongkong  #学院服务器
    #password: password

    #url: jdbc:mysql://localhost:3306/dcxevaluation?serverTimezone=Hongkong&allowMultiQueries=true
    #password: 164815

    #数据库连接池采用Druid
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化，最小，最大活跃连接数
    initialSize: 5

    minIdle: 5
    maxActive: 20
    #超时时间，单位：ms
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位:ms
    timeBetweenEvictionRunsMillis: 60000
    #一个连接的最少生存时间,单位:ms
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

server:
  port: 2020
  servlet:
    # 统一在 url 加上 /fcxevaluation 前缀
    context-path: /dcxevaluation
